/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      container: {
        center: true,
        padding: "15px",
        screens: {
          'sm': "640px",
          'md': "768px",
          'lg': "1024px",
          'xl': "1366px",
        }
      },
      fontSize: {
        'custom-sm': "6px",
        'custom-md': "13px",
        'custom-lg': "15px",
        'custom-xl': "22px",
        'custom-2xl': "40px",
        'custom-3xl': "50px",
        'custom-4xl': "80px",
        'custom-5xl': "120px",
      },
      lineHeight: {
        'custom-xs': "6px",
        'custom-sm': "7.97px",
        'custom-md': "13px",
        'custom-lg': "15px",
        'custom-xl': "18px",
        'custom-2xl': "19.92px",
        'custom-3xl': "22px",
        'custom-4xl': "22.22px",
        'custom-5xl': "26px",
        'custom-6xl': "30px",
        'custom-7xl': "39.84px",
        'custom-8xl': "44px",
        'custom-9xl': "52px",
        'custom-10xl': "70px",
        'custom-11xl': "104px",
        'custom-12xl': "90px",
      },
      colors: {
        'green': "#D2F038",
        'light-gray': "#9DC9CC",
        'dark-green': "#097980",
        'light-black': "#a6a6a6",
        'light-green': "#0D99A0",
        'aqua-green': "#00AFB5",
        'red': "#FF4242",
      },
      boxShadow: {
        'custom-xl': "0px 10px 40px 0px #41566B0D",
      },
      backgroundImage: {
        'hero-bg': "url('/public/assets/images/webp/hero-bg.webp')",
        'blue-bg': "url('/public/assets/images/webp/bg-blue.webp')",
        'green-bg': "url('/public/assets/images/webp/bg-green.webp')",
        'yellow-bg': "url('/public/assets/images/webp/bg-yellow.webp')",
        'goals-bg': "url('/public/assets/images/webp/goals-bg.webp')",
        'outsmart-bg': "url('/public/assets/images/webp/outsmart-bg.webp')",
        'tab-industry-bg': "url('/public/assets/images/webp/industry-tab-active-bg.webp')",
        'tab-proprietary-bg': "url('/public/assets/images/webp/tab-proprietary-bg.webp')",
        'tab-proprietary-mobile-bg': "url('/public/assets/images/webp/tab-proprietary-mobile-bg.webp')", 
        'tab-focused-bg': "url('/public/assets/images/webp/tab-focused-bg.webp')",
        'tab-focused-mobile-bg': "url('/public/assets/images/webp/focused-mobile-bg.webp')",
        'actual-bg': "url('/public/assets/images/webp/actual-bg.webp')",
        'marketing-bg-one': "url('/public/assets/images/webp/marketing-bg-one.webp')",
        'marketing-bg-two': "url('/public/assets/images/webp/marketing-bg-two.webp')",
        'marketing-bg-three': "url('/public/assets/images/webp/marketing-bg-three.webp')",
        'marketing-mobile-one': "url('/public/assets/images/webp/marketing-mobile-one.webp')",
        'marketing-mobile-two': "url('/public/assets/images/webp/marketing-mobile-two.webp')",
        'marketing-mobile-three': "url('/public/assets/images/webp/marketing-mobile-three.webp')",
      },
      fontFamily: {
        'space': "'space mono', sans-serif",
        'MaisonNeue': "'Maison Neue',sans-serif",
        'maisonLight': "'MaisonNeueLight',sans-serif",
        'maisonMedium': "'MaisonNeueMedium',sans-serif",
        'maisonDemi': "'MaisonNeueDemi',sans-serif",
        'maisonMono': "'MaisonNeueMono',sans-serif",
        'testSöhneSchmal': "'testSöhneSchmal',sans serif",
      }
    },
  },
  plugins: [],
}

